Repository wootecam-gugucon/shopping-mall, pull requests merged in 2023-08, with the labels that each got.

#9 config: issue 및 pr 템플릿 추가
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/pull_request_template.md
Labels: config 🔗

#10 config: issue 및 pr 템플릿 추가
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/pull_request_template.md
Labels: config 🔗

#14 chore: CI 설정 파일 작성
  .github/workflows/ci-gradle.yml
Labels: config 🔗

#13 feat: 결제 기능 구현
  src/main/java/com/gugucon/shopping/pay/application/PayService.java
  src/main/java/com/gugucon/shopping/pay/config/PayConfiguration.java
  src/main/java/com/gugucon/shopping/pay/domain/Pay.java
  src/main/java/com/gugucon/shopping/pay/dto/PayFailParameter.java
  src/main/java/com/gugucon/shopping/pay/dto/PayRequest.java
  src/main/java/com/gugucon/shopping/pay/dto/PayResponse.java
  src/main/java/com/gugucon/shopping/pay/dto/PayValidationRequest.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64Translator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/OrderIdTranslator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/PayValidator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/TossPayValidator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/dto/TossValidationRequest.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/dto/TossValidationResponse.java
  src/main/java/com/gugucon/shopping/pay/repository/PayRepository.java
  src/main/java/com/gugucon/shopping/pay/ui/PayController.java
  src/main/resources/templates/pay-fail.html
  src/main/resources/templates/pay-loading.html
  src/main/resources/templates/pay-success.html
  src/main/resources/templates/pay.html
  src/test/java/com/gugucon/shopping/pay/domain/PayTest.java
  src/test/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64TranslatorTest.java
  src/test/java/com/gugucon/shopping/pay/integration/IntegrationTest.java
  src/test/java/com/gugucon/shopping/pay/integration/PayIntegrationTest.java
Labels: feature ✨

#16 feat: Spring Security 인증 구현
  build.gradle
  src/main/java/com/gugucon/shopping/auth/config/SecurityConfig.java
  src/main/java/com/gugucon/shopping/auth/domain/vo/JwtAuthenticationToken.java
  src/main/java/com/gugucon/shopping/auth/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/gugucon/shopping/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/gugucon/shopping/auth/security/JwtAuthenticationProvider.java
  src/main/java/com/gugucon/shopping/common/config/JwtConfig.java
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/common/utils/JwtProvider.java
  src/main/java/com/gugucon/shopping/item/controller/api/CartItemController.java
  src/main/java/com/gugucon/shopping/member/argumentresolver/MemberIdArgumentResolver.java
  src/main/java/com/gugucon/shopping/member/argumentresolver/annotation/MemberId.java
  src/main/java/com/gugucon/shopping/member/config/WebMvcConfig.java
  src/main/java/com/gugucon/shopping/member/interceptor/AuthInterceptor.java
  src/main/java/com/gugucon/shopping/member/service/MemberService.java
  src/main/java/com/gugucon/shopping/order/controller/api/OrderController.java
  src/main/java/com/gugucon/shopping/order/controller/api/OrderHistoryController.java
  src/test/java/com/gugucon/shopping/auth/JwtAuthenticationProviderTest.java
  src/test/java/com/gugucon/shopping/integration/AuthIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/IntegrationTest.java
  src/test/java/com/gugucon/shopping/member/interceptor/AuthInterceptorTest.java
  src/test/java/com/gugucon/shopping/member/service/MemberServiceTest.java
  src/test/java/com/gugucon/shopping/pay/integration/PayIntegrationTest.java
Labels: feature ✨

#23 feat: 재고 기능 구현하기
  .gitignore
  src/main/java/com/gugucon/shopping/auth/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/item/domain/entity/CartItem.java
  src/main/java/com/gugucon/shopping/item/domain/entity/Product.java
  src/main/java/com/gugucon/shopping/item/domain/vo/Stock.java
  src/main/java/com/gugucon/shopping/item/dto/response/ProductResponse.java
  src/main/java/com/gugucon/shopping/item/service/CartService.java
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
  src/main/java/com/gugucon/shopping/order/domain/entity/OrderItem.java
  src/main/java/com/gugucon/shopping/order/service/OrderService.java
  src/main/resources/data.sql
  src/main/resources/static/css/page/product.css
  src/main/resources/templates/index.html
  src/test/java/com/gugucon/shopping/ShoppingApplicationTests.java
  src/test/java/com/gugucon/shopping/TestUtils.java
  src/test/java/com/gugucon/shopping/auth/JwtAuthenticationProviderTest.java
  src/test/java/com/gugucon/shopping/integration/AuthIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/CartIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/IntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/LoginIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/config/IntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/config/IntegrationTestExecutionListener.java
  src/test/java/com/gugucon/shopping/item/domain/entity/CartItemTest.java
  src/test/java/com/gugucon/shopping/item/domain/entity/ProductTest.java
  src/test/java/com/gugucon/shopping/item/domain/vo/StockTest.java
  src/test/java/com/gugucon/shopping/member/domain/vo/EmailTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderItemTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderTest.java
Labels: feature ✨, test ✅

#49 feat:프론트의 로그인 회원가입 인증 수정
  src/main/resources/static/js/login.js
  src/main/resources/templates/cart.html
  src/main/resources/templates/layouts/header.html
Labels: bug 🐞

#51 feat: 상품 조회 페이징 프론트에 반영
  src/main/resources/static/css/common/pagination.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/pagination.js
  src/main/resources/templates/index.html
Labels: feature ✨

#52 refactor: 존재하지 않는 상품, 장바구니 상품, 주문, 결제에 대한 상태코드 404로 수정
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/test/java/com/gugucon/shopping/integration/CartIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java
Labels: refactor ♻️

#53 test: 테스트 내 반복적인 회원가입 단순한 메소드로 변경
  src/test/java/com/gugucon/shopping/TestUtils.java
  src/test/java/com/gugucon/shopping/integration/AuthIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/CartIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/LoginIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
  src/test/java/com/gugucon/shopping/item/domain/entity/CartItemTest.java
  src/test/java/com/gugucon/shopping/item/domain/entity/ProductTest.java
  src/test/java/com/gugucon/shopping/item/service/CartServiceTest.java
  src/test/java/com/gugucon/shopping/item/service/ProductServiceTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderItemTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderTest.java
  src/test/java/com/gugucon/shopping/order/service/OrderServiceTest.java
  src/test/java/com/gugucon/shopping/pay/infrastructure/DefaultCustomerKeyGeneratorTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
  src/test/java/com/gugucon/shopping/utils/DomainUtils.java
Labels: test ✅

#56 refactor: OrderName 생성 로직 가독성 개선
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
Labels: refactor ♻️

#57 refactor: 도메인 내 VO 외부에서 생성 후 주입
  src/main/java/com/gugucon/shopping/item/domain/entity/CartItem.java
  src/main/java/com/gugucon/shopping/item/domain/entity/Product.java
  src/main/java/com/gugucon/shopping/item/service/CartService.java
  src/main/java/com/gugucon/shopping/member/domain/entity/Member.java
  src/main/java/com/gugucon/shopping/member/service/MemberService.java
  src/main/java/com/gugucon/shopping/pay/domain/Pay.java
  src/test/java/com/gugucon/shopping/auth/JwtAuthenticationProviderTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/item/domain/entity/CartItemTest.java
  src/test/java/com/gugucon/shopping/item/service/CartServiceTest.java
  src/test/java/com/gugucon/shopping/member/service/MemberServiceTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderItemTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderTest.java
  src/test/java/com/gugucon/shopping/order/service/OrderServiceTest.java
  src/test/java/com/gugucon/shopping/pay/domain/PayTest.java
  src/test/java/com/gugucon/shopping/utils/DomainUtils.java
Labels: refactor ♻️

#59 refactor: 결제 실패시 주문 페이지로 이동하도록 변경
  src/main/java/com/gugucon/shopping/pay/controller/PayController.java
  src/main/java/com/gugucon/shopping/pay/controller/PayPageController.java
  src/main/java/com/gugucon/shopping/pay/dto/request/PayFailRequest.java
  src/main/java/com/gugucon/shopping/pay/dto/response/PayFailResponse.java
  src/main/java/com/gugucon/shopping/pay/service/PayService.java
  src/main/resources/templates/pay-fail-popup.html
  src/main/resources/templates/pay-success.html
  src/main/resources/templates/signup.html
  src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java
Labels: refactor ♻️

#64 feat: 로깅 추가
  build.gradle
  src/main/java/com/gugucon/shopping/common/exception/GlobalControllerAdvice.java
  src/main/java/com/gugucon/shopping/common/exception/ShoppingException.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/TossPayValidator.java
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-access.xml
  src/main/resources/logback-spring.xml
Labels: feature ✨, config 🔗

#66 fix: 장바구니에 담긴 물품이 없을 때 /null 로 이동하는 현상 해결
  src/main/resources/static/js/order.js
  src/main/resources/templates/pay-fail-popup.html
  src/main/resources/templates/pay-loading-popup.html
Labels: bug 🐞

#63 test: data.sql 삭제 및 테스트 격리
  src/main/resources/data.sql
  src/test/java/com/gugucon/shopping/integration/AuthIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/CartIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/LoginIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/config/IntegrationTestExecutionListener.java
  src/test/java/com/gugucon/shopping/utils/DomainUtils.java
Labels: test ✅, refactor ♻️

#68 fix: encodedOrderId 64자 이내로 제한
  src/main/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64Translator.java
  src/test/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64TranslatorTest.java
Labels: bug 🐞

#70 chore: 기본 이미지 추가
  src/main/resources/static/assets/default.png
Labels: config 🔗

#72 build: Jacoco로 테스트 커버리지 측정
  .github/workflows/ci-gradle.yml
  build.gradle
Labels: config 🔗

#71 feat: 장바구니 물품이 품절이면 페이지에 품절 표시
  src/main/java/com/gugucon/shopping/item/dto/response/CartItemResponse.java
  src/main/resources/templates/cart.html
Labels: feature ✨

#73 feat: 상품 상세 조회 페이지 구현
  src/main/java/com/gugucon/shopping/item/controller/api/ProductController.java
  src/main/java/com/gugucon/shopping/item/controller/page/ProductPageController.java
  src/main/java/com/gugucon/shopping/item/dto/response/ProductDetailResponse.java
  src/main/java/com/gugucon/shopping/item/service/ProductService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/product-detail.html
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
Labels: feature ✨

#78 feat: Dockerfile 작성
  Dockerfile
Labels: feature ✨

#79 feat: CD 자동화
  .github/workflows/cd.yml
Labels: feature ✨

#81 feat: 별점 기능 구현
  src/main/java/com/gugucon/shopping/auth/config/SecurityConfig.java
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/item/controller/api/RateController.java
  src/main/java/com/gugucon/shopping/item/domain/entity/Rate.java
  src/main/java/com/gugucon/shopping/item/dto/request/RateCreateRequest.java
  src/main/java/com/gugucon/shopping/item/dto/response/RateResponse.java
  src/main/java/com/gugucon/shopping/item/repository/RateRepository.java
  src/main/java/com/gugucon/shopping/item/service/RateService.java
  src/main/java/com/gugucon/shopping/order/dto/response/OrderItemResponse.java
  src/main/java/com/gugucon/shopping/order/repository/OrderItemRepository.java
  src/main/resources/schema.sql
  src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
Labels: feature ✨

#80 feat: 상품 검색 결과를 주문순으로 정렬
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/item/domain/SortKey.java
  src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
  src/main/java/com/gugucon/shopping/item/service/ProductService.java
  src/main/resources/schema.sql
  src/main/resources/static/js/search.js
  src/main/resources/templates/search.html
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/item/repository/ProductRepositoryTest.java
  src/test/java/com/gugucon/shopping/utils/DomainUtils.java
Labels: feature ✨

#85 feat: 별점 기능 화면 연동
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/item/controller/api/RateController.java
  src/main/java/com/gugucon/shopping/item/controller/page/RatePageController.java
  src/main/java/com/gugucon/shopping/item/dto/response/RateDetailResponse.java
  src/main/java/com/gugucon/shopping/item/repository/RateRepository.java
  src/main/java/com/gugucon/shopping/item/service/RateService.java
  src/main/resources/templates/order-history-detail.html
  src/main/resources/templates/order-history.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/rate-popup.html
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
Labels: feature ✨

#94 fix: 배포 시간 단축
  .github/workflows/cd.yml
Labels: config 🔗

#98 refactor: 결제와 주문 리팩토링
  src/main/java/com/gugucon/shopping/auth/config/SecurityConfig.java
  src/main/java/com/gugucon/shopping/common/domain/vo/Money.java
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/item/controller/api/CartItemController.java
  src/main/java/com/gugucon/shopping/item/controller/api/ProductController.java
  src/main/java/com/gugucon/shopping/member/controlller/api/LoginController.java
  src/main/java/com/gugucon/shopping/order/controller/api/OrderController.java
  src/main/java/com/gugucon/shopping/order/domain/PayType.java
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
  src/main/java/com/gugucon/shopping/order/domain/entity/OrderItem.java
  src/main/java/com/gugucon/shopping/order/dto/request/OrderPayRequest.java
  src/main/java/com/gugucon/shopping/order/dto/response/OrderPayResponse.java
  src/main/java/com/gugucon/shopping/order/service/OrderService.java
  src/main/java/com/gugucon/shopping/pay/config/TossPayConfiguration.java
  src/main/java/com/gugucon/shopping/pay/controller/PayController.java
  src/main/java/com/gugucon/shopping/pay/controller/PayPageController.java
  src/main/java/com/gugucon/shopping/pay/domain/Pay.java
  src/main/java/com/gugucon/shopping/pay/dto/request/PointPayRequest.java
  src/main/java/com/gugucon/shopping/pay/dto/request/TossPayFailRequest.java
  src/main/java/com/gugucon/shopping/pay/dto/request/TossPayRequest.java
  src/main/java/com/gugucon/shopping/pay/dto/response/PayResponse.java
  src/main/java/com/gugucon/shopping/pay/dto/response/TossPayFailResponse.java
  src/main/java/com/gugucon/shopping/pay/dto/response/TossPayInfoResponse.java
  src/main/java/com/gugucon/shopping/pay/dto/toss/response/TossPayCreateResponse.java
  src/main/java/com/gugucon/shopping/pay/dto/toss/response/TossPayValidationResponse.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/CustomerKeyGenerator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/DefaultCustomerKeyGenerator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64Translator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/OrderIdTranslator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/PayValidator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/TossPayProvider.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/TossPayValidator.java
  src/main/java/com/gugucon/shopping/pay/infrastructure/dto/TossValidationRequest.java
  src/main/java/com/gugucon/shopping/pay/service/PayService.java
  src/main/java/com/gugucon/shopping/rate/service/RateService.java
  src/main/resources/schema.sql
  src/main/resources/static/js/cart.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/pay.js
  src/main/resources/templates/index.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/pay-loading-popup.html
  src/main/resources/templates/pay.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/search.html
  src/test/java/com/gugucon/shopping/integration/CartIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/LoginIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/PointPayIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/TossPayIntegrationTest.java
  src/test/java/com/gugucon/shopping/item/repository/ProductRepositoryTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderItemTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderTest.java
  src/test/java/com/gugucon/shopping/order/service/OrderServiceTest.java
  src/test/java/com/gugucon/shopping/pay/domain/PayTest.java
  src/test/java/com/gugucon/shopping/pay/infrastructure/DefaultCustomerKeyGeneratorTest.java
  src/test/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64TranslatorTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
Labels: refactor ♻️

#110 refactor: 시큐리티 principal 정보 수정
  src/main/java/com/gugucon/shopping/auth/domain/vo/JwtAuthenticationToken.java
  src/main/java/com/gugucon/shopping/auth/dto/MemberPrincipal.java
  src/main/java/com/gugucon/shopping/auth/security/JwtAuthenticationProvider.java
  src/main/java/com/gugucon/shopping/item/controller/api/CartItemController.java
  src/main/java/com/gugucon/shopping/member/domain/entity/Member.java
  src/main/java/com/gugucon/shopping/member/domain/vo/Gender.java
  src/main/java/com/gugucon/shopping/member/dto/request/SignupRequest.java
  src/main/java/com/gugucon/shopping/member/service/MemberService.java
  src/main/java/com/gugucon/shopping/order/controller/api/OrderController.java
  src/main/java/com/gugucon/shopping/order/controller/api/OrderHistoryController.java
  src/main/java/com/gugucon/shopping/pay/controller/PayController.java
  src/main/java/com/gugucon/shopping/point/controller/PointController.java
  src/main/java/com/gugucon/shopping/rate/controller/api/RateController.java
  src/main/resources/schema.sql
  src/main/resources/templates/signup.html
  src/test/java/com/gugucon/shopping/auth/JwtAuthenticationProviderTest.java
  src/test/java/com/gugucon/shopping/integration/AuthIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
  src/test/java/com/gugucon/shopping/item/repository/ProductRepositoryTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
  src/test/java/com/gugucon/shopping/utils/DomainUtils.java
Labels: refactor ♻️

#115 refactor: rate에 memberId 삭제
  src/main/java/com/gugucon/shopping/rate/domain/entity/Rate.java
  src/main/java/com/gugucon/shopping/rate/repository/RateRepository.java
  src/main/java/com/gugucon/shopping/rate/service/RateService.java
  src/main/resources/schema.sql
Labels: refactor ♻️

#112 feat: 운영 서버 배포 자동화
  .github/workflows/cd-prod.yml
  Dockerfile
Labels: feature ✨

#117 feat: 나이대 정보와 생년월일 변환 로직 구현
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/member/domain/vo/BirthYearRange.java
  src/test/java/com/gugucon/shopping/member/domain/vo/BirthYearRangeTest.java
Labels: feature ✨

#118 feat: 주문 목록 페이지네이션
  src/main/java/com/gugucon/shopping/item/controller/api/ProductController.java
  src/main/java/com/gugucon/shopping/item/domain/SortKey.java
  src/main/java/com/gugucon/shopping/item/service/ProductService.java
  src/main/java/com/gugucon/shopping/order/controller/api/OrderHistoryController.java
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
  src/main/java/com/gugucon/shopping/order/repository/OrderRepository.java
  src/main/java/com/gugucon/shopping/order/service/OrderService.java
  src/main/java/com/gugucon/shopping/pay/repository/PayRepository.java
  src/main/resources/static/js/search.js
  src/main/resources/templates/order-history.html
  src/main/resources/templates/search.html
  src/test/java/com/gugucon/shopping/integration/OrderHistoryIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
Labels: feature ✨

#126 refactor: 로그인 화면 영문 변경
  src/main/resources/templates/login.html
Labels: refactor ♻️

#124 refactor: 상품 상세 페이지에 전부 접근 가능
  src/main/java/com/gugucon/shopping/item/dto/response/CartItemResponse.java
  src/main/java/com/gugucon/shopping/order/dto/response/OrderItemResponse.java
  src/main/resources/templates/cart.html
  src/main/resources/templates/index.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/order-history-detail.html
  src/main/resources/templates/order-history.html
  src/main/resources/templates/pay-success.html
  src/main/resources/templates/search.html
Labels: bug 🐞

#122 feat: 통계 테이블 스키마 작성
  src/main/java/com/gugucon/shopping/item/domain/entity/OrderStat.java
  src/main/java/com/gugucon/shopping/item/domain/entity/RateStat.java
  src/main/java/com/gugucon/shopping/item/repository/OrderStatRepository.java
  src/main/java/com/gugucon/shopping/item/repository/RateStatRepository.java
  src/main/java/com/gugucon/shopping/item/repository/dto/SimpleOrderStatDto.java
  src/main/java/com/gugucon/shopping/item/repository/dto/SimpleRateStatDto.java
  src/main/java/com/gugucon/shopping/item/service/StatDataGenerator.java
  src/main/resources/schema.sql
Labels: feature ✨

#123 feat: 현재 접속한 회원과 성별 및 나이대가 같은 주문들의 평균 별점 조회 기능 구현
  src/main/java/com/gugucon/shopping/member/repository/MemberRepository.java
  src/main/java/com/gugucon/shopping/member/service/MemberService.java
  src/main/java/com/gugucon/shopping/rate/controller/api/RateController.java
  src/main/java/com/gugucon/shopping/rate/dto/response/RateDetailResponse.java
  src/main/java/com/gugucon/shopping/rate/repository/RateRepository.java
  src/main/java/com/gugucon/shopping/rate/service/RateService.java
  src/main/resources/application-test.yml
  src/test/java/com/gugucon/shopping/integration/LoginIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
Labels: feature ✨

#120 refactor: 토스 결제 시 필요없는 데이터 제거
  src/main/java/com/gugucon/shopping/pay/dto/response/TossPayInfoResponse.java
  src/main/java/com/gugucon/shopping/pay/service/PayService.java
  src/main/resources/templates/pay-loading-popup.html
  src/main/resources/templates/pay.html
  src/test/java/com/gugucon/shopping/integration/TossPayIntegrationTest.java
Labels: refactor ♻️

#119 refactor: 회원가입시 나이 제약조건 추가
  src/main/java/com/gugucon/shopping/member/domain/vo/BirthYearRange.java
  src/main/java/com/gugucon/shopping/member/service/MemberService.java
  src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
  src/test/java/com/gugucon/shopping/member/domain/vo/BirthYearRangeTest.java
Labels: bug 🐞, refactor ♻️

#133 fix: 시작일을 포함하도록 제약 조건을 수정한다
  src/main/java/com/gugucon/shopping/member/domain/vo/BirthYearRange.java
Labels: bug 🐞

#130 feat: 상품 전체 조회 시 필터링 추가
  src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
  src/main/java/com/gugucon/shopping/item/controller/api/ProductController.java
  src/main/java/com/gugucon/shopping/item/domain/SearchCondition.java
  src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
  src/main/java/com/gugucon/shopping/item/service/ProductService.java
  src/main/java/com/gugucon/shopping/member/config/WebConfig.java
  src/main/java/com/gugucon/shopping/member/infrastructure/converter/StringToBirthYearRangeConverter.java
  src/main/java/com/gugucon/shopping/member/infrastructure/converter/StringToGenderConverter.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
Labels: feature ✨

#137 feat: 통계 테이블 업데이트 로직 작성
  src/main/java/com/gugucon/shopping/item/repository/OrderStatRepository.java
  src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
  src/main/java/com/gugucon/shopping/item/repository/RateStatRepository.java
  src/main/java/com/gugucon/shopping/pay/controller/PayController.java
  src/main/java/com/gugucon/shopping/pay/service/PayService.java
  src/main/java/com/gugucon/shopping/rate/controller/api/RateController.java
  src/main/java/com/gugucon/shopping/rate/service/RateService.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
Labels: feature ✨

#103 fix: 재고 감소 트랜잭션에 락 추가
  src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
  src/main/java/com/gugucon/shopping/order/repository/OrderRepository.java
  src/main/java/com/gugucon/shopping/order/service/OrderService.java
  src/main/java/com/gugucon/shopping/pay/service/PayService.java
Labels: bug 🐞

#134 feat: 상품 추천 기능 구현
  src/main/java/com/gugucon/shopping/common/dto/response/SlicedResponse.java
  src/main/java/com/gugucon/shopping/item/controller/api/ProductController.java
  src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
  src/main/java/com/gugucon/shopping/item/service/ProductService.java
  src/main/resources/templates/product-detail.html
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
Labels: feature ✨

#140 refactor: 별점 높은 순 정렬에 countQuery를 적용한다
  src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
Labels: refactor ♻️

#136 feat: 물품 상세 페이지에 현재 접속한 유저에 따른 평균 별점 항목 추가
  src/main/java/com/gugucon/shopping/rate/service/RateService.java
  src/main/resources/templates/product-detail.html
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
Labels: feature ✨

#144 refactor: PayService 리팩토링
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
  src/main/java/com/gugucon/shopping/order/service/OrderService.java
  src/main/java/com/gugucon/shopping/pay/service/PayService.java
Labels: feature ✨

#147 142 성별 나이별 검색 필터링 기능 프론트 연동
  src/main/resources/static/css/common/index.css
  src/main/resources/static/css/common/search.css
  src/main/resources/static/css/page/product.css
  src/main/resources/static/js/search.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/searchbar.html
  src/main/resources/templates/search.html
Labels: feature ✨

#143 chore: 테스트 불가능한 코드를 Jacoco 검사에서 제외
  build.gradle
  lombok.config
  src/main/java/com/gugucon/shopping/item/domain/entity/RateStat.java
  src/main/java/com/gugucon/shopping/item/repository/OrderStatRepository.java
  src/main/java/com/gugucon/shopping/item/repository/RateStatRepository.java
  src/main/java/com/gugucon/shopping/item/repository/dto/SimpleOrderStatDto.java
  src/main/java/com/gugucon/shopping/item/repository/dto/SimpleRateStatDto.java
  src/main/java/com/gugucon/shopping/item/service/StatDataGenerator.java
Labels: config 🔗

#153 148 모니터링 대시보드 구축
  build.gradle
  src/main/resources/application.yml
Labels: config 🔗

#151 fix: 페이지 슬라이딩 제거
  src/main/resources/templates/product-detail.html
Labels: bug 🐞

#154 test: 테스트 커버리지 높이기
  build.gradle
  src/main/java/com/gugucon/shopping/order/domain/PayType.java
  src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
  src/main/java/com/gugucon/shopping/order/dto/request/OrderPayRequest.java
  src/main/java/com/gugucon/shopping/order/scheduler/OrderCancelService.java
  src/main/java/com/gugucon/shopping/order/service/OrderService.java
  src/test/java/com/gugucon/shopping/common/utils/JwtProviderTest.java
  src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/PointPayIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
  src/test/java/com/gugucon/shopping/integration/TossPayIntegrationTest.java
  src/test/java/com/gugucon/shopping/item/domain/SearchConditionTest.java
  src/test/java/com/gugucon/shopping/member/infrastructure/converter/StringToBirthYearRangeConverterTest.java
  src/test/java/com/gugucon/shopping/member/infrastructure/converter/StringToGenderConverterTest.java
  src/test/java/com/gugucon/shopping/order/domain/entity/OrderTest.java
  src/test/java/com/gugucon/shopping/order/scheduler/OrderCancelServiceTest.java
  src/test/java/com/gugucon/shopping/order/service/OrderServiceTest.java
  src/test/java/com/gugucon/shopping/pay/infrastructure/OrderIdBase64TranslatorTest.java
  src/test/java/com/gugucon/shopping/point/service/PointServiceTest.java
  src/test/java/com/gugucon/shopping/utils/ApiUtils.java
Labels: test ✅

#155 refactor: 중복 인덱스 제거
  src/main/resources/schema.sql
Labels: refactor ♻️

#161 feat: 물품 주문자들의 성별 및 나이대별 평균 별점 구현
  src/main/java/com/gugucon/shopping/auth/config/SecurityConfig.java
  src/main/java/com/gugucon/shopping/rate/controller/api/RateController.java
  src/main/java/com/gugucon/shopping/rate/dto/response/GroupRateResponse.java
  src/main/java/com/gugucon/shopping/rate/repository/RateRepository.java
  src/main/java/com/gugucon/shopping/rate/repository/dto/GroupAverageRateDto.java
  src/main/java/com/gugucon/shopping/rate/service/RateService.java
  src/main/resources/templates/product-detail.html
  src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
Labels: feature ✨

#159 feat: 프론트에 api 추가하기
  src/main/java/com/gugucon/shopping/item/dto/response/ProductDetailResponse.java
  src/main/resources/static/css/common/checkbox.css
  src/main/resources/static/css/common/highlight-text.css
  src/main/resources/static/css/common/nav.css
  src/main/resources/static/css/common/pagination.css
  src/main/resources/static/css/common/primary-button.css
  src/main/resources/static/css/common/search.css
  src/main/resources/static/favicon.ico
  src/main/resources/templates/cart.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/order-history-detail.html
  src/main/resources/templates/order-history.html
  src/main/resources/templates/pay.html
  src/main/resources/templates/point-charge.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/search.html
  src/main/resources/templates/signup.html
  src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
Labels: feature ✨
